### ISSUE TITLE
Portfolio Object missing the ID Key

### ISSUE THREAD

**Issue by brightbrain20** [ehmaddd/mobile-first-portfolio#17]
## Hi @ehmaddd,
 good job so far. I would like to suggest that your portfolio object has an ID key with values of 1, 2,3 and so on

This way, each element in the object can be accessed without difficulty.

<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>

**Comment by ehmaddd** [comment]
Yes you have mentioned it right. But for the time being, these a small number of items, I will surely implement it when I'll shift it to the database, or maybe next revision. Much appreciated
