### ISSUE TITLE
BUG : misplacement of ID with class name

### ISSUE THREAD

**Issue by brightbrain20** [ehmaddd/mobile-first-portfolio#18]
https://github.com/ehmaddd/mobile-first-portfolio/blob/4ef096b71707b6d67dee17f2dbc3b397c79ce091/script.js#L125

- Inside your html there is no element with the Id #drop-link 
- some element have the class name drop-link
- due to which certain bugs are present in the code. 
## way out
please change the ID to CLASS

<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>

**Comment by ehmaddd** [comment]
Let me give you a good news that I've settled the issue by removing bug with change in code. Good to listen from your side.
